// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNle9rb1lWGCUEEnjQmwQL21gwVL6bFw0',
    appId: '1:319742121014:web:f53048579fc3386ad93497',
    messagingSenderId: '319742121014',
    projectId: 'econaija-d1fb5',
    authDomain: 'econaija-d1fb5.firebaseapp.com',
    storageBucket: 'econaija-d1fb5.appspot.com',
    measurementId: 'G-K8EMZSGKVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3ObOwTKy9FVft7Q888GnOtoaY0jyZ-o',
    appId: '1:319742121014:android:1954ece8fe05a5dad93497',
    messagingSenderId: '319742121014',
    projectId: 'econaija-d1fb5',
    storageBucket: 'econaija-d1fb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOaidv1Fm8s_dzlY0uRkVncZqcwTpBAU',
    appId: '1:319742121014:ios:a4133744790bf1e5d93497',
    messagingSenderId: '319742121014',
    projectId: 'econaija-d1fb5',
    storageBucket: 'econaija-d1fb5.appspot.com',
    iosBundleId: 'com.example.econaija',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOaidv1Fm8s_dzlY0uRkVncZqcwTpBAU',
    appId: '1:319742121014:ios:ed1b1038c12a1d1dd93497',
    messagingSenderId: '319742121014',
    projectId: 'econaija-d1fb5',
    storageBucket: 'econaija-d1fb5.appspot.com',
    iosBundleId: 'com.example.econaija.RunnerTests',
  );
}
